name             'graylog'
maintainer       'Chris Aumann'
maintainer_email 'me@chr4.org'
license          'GNU Public License 3.0'
description      'Installs/Configures graylog'
long_description 'Installs/Configures graylog'
version          '1.0.2'
depends          'apt'
depends          'mongodb'
depends          'ark'
